FullProject/EtOrder/Online_Food_Delivery/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
from Product.views import order_conform

urlpatterns = [
    path('admin/', admin.site.urls),
    path('repo/', include('reporter.urls')),
    path('product/', include('Product.urls')),
    path('',views.index,name='index'),
    path('order/conformed/', order_conform, name='Product_order_conform'),
    path('accounts/',include('accounts.urls')),
    path('logout/',views.userLogout,name='logout'),
    path('customerDash/',views.customerDash,name='customerDash'),
    path('staffDash/',views.staffDash,name='staffDash'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FullProject/EtOrder/Product/urls.py
from django.urls import path

from Product import views 
urlpatterns = [
    
     # urls for Product
   
    path('', views.CompanyListView.as_view(), name='Company_company_list'),
    path('products/company/<slug:slug>/', views.ProductListView.as_view(), name='Product_product_list'),
    path('product/detail/<slug:slug>/', views.ProductDetailView.as_view(), name='Product_product_detail'),

    # urls for order
    path('orders/', views.OrderListView.as_view(), name='Product_order_list'),
    #path('order/conformed/', views.order_conform, name='Product_order_conform'),
    path('order/create/<slug:slug>', views.OrderCreateView.as_view(), name='Product_order_create'),
    path('order/detail/<slug:slug>/', views.OrderDetailView.as_view(), name='Product_order_detail'),
   
]

FullProject/EtOrder/accounts/urls.py
from django.urls import path
from accounts import views


app_name='accounts'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('registerCustomer/',views.registerCustomer,name='registerCustomer'),
    path('registerStaff/',views.registerStaff,name='registerStaff'),
    path('login/',views.userLogin,name='userLogin'),
    path('dashboard',views.dashboard,name='dashboard'),
    
   
]

FullProject/EtOrder/accounts/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.contrib.gis.db import models as gis_models
from django.db.models import Manager as GeoManager
# Create your models here.

class Customer(models.Model):
    customer=models.OneToOneField(User,on_delete=models.CASCADE)
    idno=models.IntegerField(blank=False)
    customer_type=models.CharField(max_length=256,blank=False)
    phone=models.IntegerField(default=0)
    ip_location = gis_models.PointField(null=True, blank=True, dim=3)
    
    is_customer=models.BooleanField(default=True)

    def __str__(self):
        return self.customer.username

class Staff(models.Model):
    staff=models.OneToOneField(User,on_delete=models.CASCADE)
    Staff_subject=models.CharField(max_length=256,blank=False)
    phone=models.IntegerField(default=0)
    is_customer=models.BooleanField(default=False)

    def __str__(self):
        return self.staff.username

FullProject/EtOrder/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import Customer,Staff

class customerForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=['first_name','last_name','username','email','password']

BRANCH_CHOICES = (
    ('COMPS','COMPS'),
    ('IT','IT'),
    ('EXTC','EXTC')
)
class customerAddForm(forms.ModelForm):
    branch=forms.CharField(widget=forms.Select(choices=BRANCH_CHOICES))
    class Meta():
        model=Customer
        fields=['idno','branch']

class staffForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=['first_name','last_name','username','email','password']

SUBJECT_CHOICES=(
    ('DS','Data Structures'),
    ('DLD','Digital Logic Design'),
    ('DM','Discrete Mathematics'),
    ('LA','Linear Algebra')
)

class staffAddForm(forms.ModelForm):
    subject=forms.CharField(widget=forms.Select(choices=SUBJECT_CHOICES))
    class Meta():
        model=Staff
        fields=['subject','phone']


        

FullProject/EtOrder/accounts/views.py
from django.shortcuts import render,redirect
from accounts.forms import customerForm,customerAddForm,staffForm,staffAddForm
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from accounts.models import Customer,Staff 
from django.contrib.auth.models import User

# Create your views here.

def index(request):
    return render(request,'accounts/index.html')

@login_required
def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    return render(request,'accounts/register.html')

def registerCustomer(request):
    registered=False
    if request.method=='POST':
        var_customerForm=customerForm(request.POST)
        var_customerAddForm=customerAddForm(request.POST)
        if var_customerForm.is_valid() and var_customerAddForm.is_valid():
            customerprimary=var_customerForm.save()
            customerprimary.set_password(customerprimary.password)
            customerprimary.save()
            customerAdd=var_customerAddForm.save(commit=False)
            customerAdd.customer=customerprimary
            customerAdd.save()
            registered=True
    else:
        var_customerForm=customerForm()
        var_customerAddForm=customerAddForm()
    return render(request,'accounts/registerCustomer.html',{'var_customerForm':var_customerForm,'var_customerAddForm':var_customerAddForm,'registered':registered})


def registerStaff(request):
    registered=False
    if request.method=='POST':
        var_staffForm=staffForm(request.POST)
        var_staffAddForm=staffAddForm(request.POST)
        if var_staffForm.is_valid() and var_staffAddForm.is_valid():
            staffprimary=var_staffForm.save()
            staffprimary.set_password(staffprimary.password)
            staffprimary.save()
            staffAdd=var_staffAddForm.save(commit=False)
            staffAdd.staff=staffprimary
            staffAdd.save()
            registered=True
    else:
        var_staffForm=staffForm()
        var_staffAddForm=staffAddForm()
    return render(request,'accounts/registerStaff.html',{'var_staffForm':var_staffForm,'var_staffAddForm':var_staffAddForm,'registered':registered})
    
def userLogin(request):
    invalidlogin=False
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            invalidlogin=True
            return redirect('/accounts/login/')
    else:
        return render(request,'accounts/login.html',{'invalidlogin':invalidlogin})

@login_required
def dashboard(request):
    try:
        current=Customer.objects.get(customer=request.user)
    except Customer.DoesNotExist:
        current=Staff.objects.get(staff=request.user)
    if current.is_customer:
        return redirect('/customerDash/')
    else:
        return redirect('/staffDash/')
    return render(request,'accounts/dashboard.html')

    

def customerDash(request):
    return redirect('/product/')

def staffDash(request):
    return redirect('/repo/')

FullProject/EtOrder/templates/accounts/accountsbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>EtOrder</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url "index" %}">EtOrder</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
                </li>
                
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "accounts:register" %}">Register</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "accounts:dashboard" %}">Shop</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "logout" %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "accounts:userLogin" %}"
                        >Login</a
                        >
                    </li>
                {% endif %}
               
            </ul>
            
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

FullProject/EtOrder/templates/accounts/customerDash.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Customers Dash</h2>
        <hr>
    </div>
</div>


{% endblock %}

FullProject/EtOrder/templates/accounts/dashboard.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}
{% endblock %}

FullProject/EtOrder/templates/accounts/index.html
{% extends 'accounts/accountsbase.html' %}
{% load static %}

{% block body_block %}


<div class="slideshow-container">
<h1 class="display-3">EtOrder</h1>
        <p class="lead">Make Product Distribution Easier and Accessable 24/7</p>
        <hr class="my-2">
        <p>Order Products of Your Choice directly from Our Staff Members</p>
<img src="{% static '/img/12.jpg' %}" style="width:100%" alt="My image1">
        
{% endblock %}

FullProject/EtOrder/templates/accounts/login.html
{% extends "accounts/accountsbase.html" %}
{% block body_block %}

<div class="jumbotron">
    {% if invalidlogin %}
        <h3>Please enter correct login details!</h3>
    {% endif %}
    <form action="{% url 'accounts:userLogin' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password: </label>
        <input type="password" name="password" placeholder="Enter Password">
        <input type="Submit" value="Login">
    </form>
</div>

{% endblock %}

FullProject/EtOrder/templates/accounts/register.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1 class="display-3">Register Here!</h1>
   
    <hr class="my-2">
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url "accounts:registerCustomer" %}" role="button">I'm a Customer</a>
        <a class="btn btn-primary btn-lg" href="{% url "accounts:registerStaff" %}" role="button">I'm a Staff Member</a>
    </p>
</div>

{% endblock %}

FullProject/EtOrder/templates/accounts/registerCustomer.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}

<div class="jumbotron">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Customers:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_customerForm.as_p }}
            {{ var_customerAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>


{% endblock %}

FullProject/EtOrder/templates/accounts/registerStaff.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}

<div class="jumbotron">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Staff Members:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_staffForm.as_p }}
            {{ var_staffAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>


{% endblock %}

FullProject/EtOrder/templates/accounts/registerStudent.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}

<div class="jumbotron">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Customers:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_customerForm.as_p }}
            {{ var_customerAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>


{% endblock %}

FullProject/EtOrder/templates/accounts/registerTeacher.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}

<div class="jumbotron">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Staff Members:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_staffForm.as_p }}
            {{ var_staffAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>


{% endblock %}

FullProject/EtOrder/templates/accounts/staffDash.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Staff Dash</h2>
        <hr>
    </div>
</div>

{% endblock %}

FullProject/EtOrder/templates/accounts/studentDash.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Customers Dash</h2>
        <hr>
    </div>
</div>


{% endblock %}

FullProject/EtOrder/templates/accounts/teacherDash.html
{% extends 'accounts/accountsbase.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Staff Dash</h2>
        <hr>
    </div>
</div>

{% endblock %}